seed: 42
output_dir: "runs"

dataset:
  name: "FreqShape"
  params:
    base_path: "./data/FreqShape"  # where Timex expects data
    split_no: 2

models:
  - name: "Transformer"
    params:
      d_model: 64
      nhead: 4
      num_layers: 1
      lr: 1e-3
      epochs: 5
      batch_size: 32
    single_label: True
  - name: "LSTM"
    params:
      hidden_dim: 64
      num_layers: 1
      lr: 1e-3
      epochs: 5
      batch_size: 32
    single_label: True

explainers: ["Grad", 
            # "IG", 
            "LIME"]
metrics: ["Faithfulness", 
          "Consistency",
          # "GTAgreement", 
          # "TopKIoU"
          ]
