seed: 42
output_dir: "runs"

dataset:
  name: "PAM"
  params:
    base_path: "./data/PAM" 
    gethalf: True
models:
  - name: "Transformer"
    params:
      d_model: 64
      nhead: 4
      num_layers: 1
      lr: 1e-3
      epochs: 5
      batch_size: 32
      num_classes: 8

  - name: "LSTM"
    params:
      hidden_dim: 64
      num_layers: 1
      lr: 1e-3
      epochs: 5
      batch_size: 32

explainers: 
  - name: "Grad"
    params:
  # - name: "IG"
  #   params:
  #     steps: 30
  - name: "LIME"
    params:
metrics: 
  - name: "Faithfulness"
    params:
      k_ratio: [0.2, 0.3, 0.4, 0.5]
  - name: "Consistency"
    params:
      # k_ratio: 0.2
  - name: "Stability"
    params:
      # k_ratio: 0.2
  - name: "Comprehensiveness"
    params:
      k_ratio: [0.1, 0.2, 0.3]
  - name: "Sufficiency"
    params:
      k_ratio: [0.1, 0.2, 0.3]