seed: 42
output_dir: "runs"

dataset:
  name: "SwitchDataset"
  params:
    data_dir: "./data/simulated_switch_data"
    # x_train_pkl: "state_dataset_x_train.pkl"
    # x_test_pkl:  "state_dataset_x_test.pkl"
    # y_train_pkl: "state_dataset_y_train.pkl"
    # y_test_pkl:  "state_dataset_y_test.pkl"
    # transpose_to_t_first: true
    # cast_float32: true
    # cast_int64: true
    # limit_train: null
    # limit_test: null

models:
  - name: "LSTM"
    params:
      input_dim: 3     # set to your D (features)
      hidden_dim: 64
      num_layers: 1
      num_classes: 2   # set to your number of classes
      lr: 1e-3
      epochs: 3
      batch_size: 64
    single_label: True

explainers: 
  # - name: "Grad"
  #   params:
  # - name: "IG"
  #   params:
  #     steps: 30
  # - name: "LIME"
  #   params:
  # - name: "DeepLIFT"
  #   params:
  # - name: "Dynamask"
  #   params:
  #     # area_list:                       # float list; e.g. [0.1,0.2] or null
  #     num_class: 4
  #     blur_type: 'gaussian'                  # one of [gaussian, fadema]
  #     # deletion_mode:                   # boolean or null
  #     # size_reg_factor_dilation:                    # integer or null
  #     # time_reg_factor:                    # integer or null
  #     # loss:                       # one of [logloss, ce] or null
  #     epoch: 200                      # # of Dynamask epochs
  #     use_last_timestep_only: True                # "True" or "False" or null
  # - name: "FIT"
  #   params:
  #     epochs_gen: 150                     # # of generator training epochs
  #     feature_size: 1
  #     num_samples: 10
  - name: "WINIT"
    params:
      epochs_gen: 150                     # # of generator training epochs
      num_features: 1
      num_samples: 10
      window_size: 10
      conditional: False # Not possible for num_feature = 1
      joint: True
      metric: "kl" # ["kl", "pd", or "js"]



metrics: 
  - name: "Faithfulness"
    params:
      k_ratio: [0.2, 0.3, 0.4, 0.5]
  - name: "Consistency"
    params:
      # k_ratio: 0.2
  - name: "Stability"
    params:
      # k_ratio: 0.2
  - name: "Comprehensiveness"
    params:
      k_ratio: [0.1, 0.2, 0.3]
  - name: "Sufficiency"
    params:
      k_ratio: [0.1, 0.2, 0.3]
  - name: "Accuracy"
    params:
      k_ratio: [0.1, 0.2, 0.3]
  - name: "CrossEntropy"
    params:
      k_ratio: [0.1, 0.2, 0.3]
  - name: "ExplanationAUC"
    params:
